version: '3.8'

services:
  app:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}-app
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && npx nest start --watch"
