name: CD App [dev]

on:
  push:
    branches:
      - master
    paths-ignore:
      - infra/**
      - .github/**
      - README.md

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-20.04

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_SA_KEY: ${{ secrets.GCP_DEV_SA_KEY }}
      GCP_REPOSITORY: ${{ secrets.GCP_DEV_REPOSITORY }}
      GCP_IMAGE_NAME: ${{ secrets.GCP_DEV_IMAGE_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.GCP_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCP_PROJECT_ID }}-dev-service \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.GCP_IMAGE_NAME }}:latest \
            --platform managed \
            --region=${{ env.GCP_REGION }} \
            --allow-unauthenticated
