name: manual CD

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Which environment to deploy to"
        default: "dev"
        required: true
        options:
          - "dev"
          - "prod"

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-20.04

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

      GCP_SA_KEY: ${{ (github.event.inputs.env == 'prod' && secrets.GCP_PROD_SA_KEY) || secrets.GCP_DEV_SA_KEY }}
      GCP_REPOSITORY: ${{ (github.event.inputs.env == 'prod' && secrets.GCP_PROD_REPOSITORY) || secrets.GCP_DEV_REPOSITORY }}
      GCP_IMAGE_NAME: ${{ (github.event.inputs.env == 'prod' && secrets.GCP_PROD_IMAGE_NAME) || secrets.GCP_DEV_IMAGE_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.GCP_IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCP_PROJECT_ID }}-${{ github.event.inputs.env }}-service \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.GCP_IMAGE_NAME }}:latest \
            --platform managed \
            --region=${{ env.GCP_REGION }} \
            --allow-unauthenticated
