name: manual CD Infra

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Which environment to deploy to"
        default: "dev"
        required: true
        options:
          - "dev"
          - "prod"
      apply:
        type: boolean
        description: "Do you want to apply changes?"
        default: false
        required: true

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./infra/environments/${{ github.event.inputs.env }}

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ github.event.inputs.env == 'prod' && secrets.GCP_PROD_SA_KEY || secrets.GCP_DEV_SA_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        if: ${{ github.event.inputs.apply == 'true' }}
        run: terraform apply -auto-approve
